/bin/echo 30 > /sys/class/gpio/export
/bin/echo 32 > /sys/class/gpio/export
/bin/echo in > /sys/class/gpio/gpio30/direction
/bin/echo out > /sys/class/gpio/gpio32/direction
/bin/echo 31 > /sys/class/gpio/export
/bin/echo 62 > /sys/class/gpio/export
/bin/echo in > /sys/class/gpio/gpio31/direction
/bin/echo out > /sys/class/gpio/gpio62/direction
/bin/echo 33 > /sys/class/gpio/export
/bin/echo in > /sys/class/gpio/gpio33/direction
